blank_issues_enabled: false
contact_links:
  - name: indexd issues
    url: https://github.com/SiaFoundation/indexd/issues/new/choose
    about: Please create indexd UI issues on the indexd repo.
  - name: renterd issues
    url: https://github.com/SiaFoundation/renterd/issues/new/choose
    about: Please create renterd UI issues on the renterd repo.
  - name: hostd issues
    url: https://github.com/SiaFoundation/hostd/issues/new/choose
    about: Please create hostd UI issues on the hostd repo.
  - name: walletd issues
    url: https://github.com/SiaFoundation/walletd/issues/new/choose
    about: Please create walletd UI issues on the walletd repo.
  - name: other issues
    url: https://github.com/SiaFoundation/web/issues/new?template=blank.md
    about: Create other issues on the web repo.
  - name: Sia Community Discord
    url: https://discord.gg/sia
    about: Join the Sia community discord for more help with Sia.
